### ISSUE TITLE
你好，最新的mac版本，我这无法拖拽文件目录了

### ISSUE THREAD

**Issue by oko03k** [yongplus/tinypng#10]

**Comment by houkhan** [comment]
好想不止没法拖拽文件了，选择相关目录也无法读取其中的文件

**Comment by houkhan** [comment]
我回退到https://github.com/yongplus/tinypng/releases/tag/1.0.1这版本好了，可能上个版本修改什么影响到了

**Comment by yongplus** [comment]
感谢反馈，Mac在家里，晚上回去看下

**Comment by yongplus** [comment]
> 我回退到 https://github.com/yongplus/tinypng/releases/tag/1.0.1 这版本好了，可能上个版本修改什么影响到了

已接近 仓库里下新包 新增的大小范围设置影响  升级的用户上限有bug 可以手动修改下大小范围

**Comment by yongplus** [comment]
> 我回退到 https://github.com/yongplus/tinypng/releases/tag/1.0.1 这版本好了，可能上个版本修改什么影响到了

已更新 仓库里下新包 新增的大小范围设置影响 升级的用户上限有bug 可以手动修改下大小范围
