### ISSUE TITLE
图片尺寸会被压缩至很小

### ISSUE THREAD

**Issue by mirai027** [yongplus/tinypng#11]
压缩前：

![image](https://user-images.githubusercontent.com/37301565/226509397-1508bd29-30ec-4eee-98df-450d87954c81.png)

压缩：

![image](https://user-images.githubusercontent.com/37301565/226509450-32f7851d-cc06-45c1-abc1-b802509b981d.png)

压缩后：

![image](https://user-images.githubusercontent.com/37301565/226509475-859c3443-7d95-438f-bab8-a3ee86da88e6.png)

**Comment by yjw199596** [comment]
我也遇到这个问题了  图片的尺寸也会被压缩，希望作者解决一下

**Comment by yongplus** [comment]
> 我也遇到这个问题了 图片的尺寸也会被压缩，希望作者解决一下

是否在官网测试过？偶然还是100%复现？能否提供下原图片link，或者发送到邮箱yongplus@foxmail.com

**Comment by yjw199596** [comment]
> > 我也遇到这个问题了 图片的尺寸也会被压缩，希望作者解决一下
> 
> 是否在官网测试过？偶然还是100%复现？能否提供下原图片link，或者发送到邮箱[yongplus@foxmail.com](mailto:yongplus@foxmail.com)

官网测试了 没问题的
图片是从figma下载的切片  可以打包发你

**Comment by mirai027** [comment]
> > 我也遇到过这个问题了图片的尺寸也会被压缩，希望作者解决一下
> 
> 是不是在官网测试过？偶还是100%复现？可以提供下图片链接，或者发到邮箱[yongplus@foxmail.com](mailto:yongplus@foxmail.com)

官网不会压缩尺寸，所有图片都100%浮现。系统是Window11。

**Comment by mirai027** [comment]
> > > > 我也遇到过这个问题了图片的尺寸也会被压缩，希望作者解决一下
> > > 
> > > 
> > > 是不是在官网测试过？偶还是100%复现？可以提供下图片链接，或者发到邮箱[yongplus@foxmail.com](mailto:yongplus@foxmail.com)
> > 
> > 
> > 官网不会压缩尺寸，所有图片都100%复现。系统是Window11。
> 
> 发我下图片吧 谢谢，[yongplus@foxmail.com](mailto:yongplus@foxmail.com)

已发送

**Comment by yongplus** [comment]
谢谢，用API模式就好了，目测是官方调整了接口，我这边测试没问题后重新发个包

**Comment by mirai027** [comment]
> 谢谢，用API模式就好了，目测是官方调整了接口，我这边测试没问题后重新发个包

感谢，辛苦了！

**Comment by yongplus** [comment]
[Tinypng-Windows.zip](https://github.com/yongplus/tinypng/files/11026270/Tinypng-Windows.zip)
这个附件包是最新修改的，可以用这个
