### ISSUE TITLE
免Key模式只能压缩20张，不能压缩20张以上吗？

### ISSUE THREAD

**Issue by Cowboy-Shuai** [yongplus/tinypng#16]
Key模式可以超过20张，免Key模式只能压缩20张（不知道是不是就是这么设计的），
下面这个项目好像可以超过20张的限制，能不能**考虑结合一下再加一个超过20张的免Key模式**
[TinyImage](https://github.com/focusbe/tinyImage)

**Comment by yongplus** [comment]
之前测试过，目前官方是通过Socket客户端的IP来限制的，此方式实现绕过限制需要IP成本投入。

你提供这个仓库根据代码走查，可以看到
https://github.com/focusbe/tinyImage/blob/master/main/engine/index.js#L156
157行~166行并没有将请求API的错误抛出做提示，函数的imageData变量的参数采用了复写方案，在API出错的情况是将图片源数据单纯重新写入一遍。
