### ISSUE TITLE
windows客户端UI

### ISSUE THREAD

**Issue by yjw199596** [yongplus/tinypng#7]
![image](https://user-images.githubusercontent.com/59904710/204410408-65259a4c-91cc-4bf8-91b6-b89b3b8b3c12.png)
Windows客户端UI问题，图标文字显示不全，不管怎么拉大窗口，都是这样，希望能更新一下，谢谢啦

**Comment by yongplus** [comment]
win11系统吗？

**Comment by yjw199596** [comment]
是的

**Comment by Rango965** [comment]
MainWindow::_buildTopBtns
按钮宽度写死了

**Comment by yongplus** [comment]
目前缺少win11环境定位和调试，这个问题后续解决。
