### ISSUE TITLE
不支持webp 格式？

### ISSUE THREAD

**Issue by houkhan** [yongplus/tinypng#8]
不支持webp 格式？
https://tinypng.com/ 官方网页压缩是支持的
可否支持？

**Comment by yongplus** [comment]
win包已加上webp格式支持，到下面链接下载新版
https://github.com/yongplus/tinypng/tree/master/Installer

**Comment by houkhan** [comment]
mac 呢 什么时候支持呢

**Comment by yongplus** [comment]
我空了发个包

**Comment by yongplus** [comment]
> mac 呢 什么时候支持呢
到这里下载最新包：
https://github.com/yongplus/tinypng/tree/master/Installer
